version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    ports:
      - "3555:3555"
    environment:
      - PORT=3555
      - GOOGLE_CLIENT_ID=788767528235-jh3gjvl3nc3nvq32ik03bbtdreuvklec.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - NEXTAUTH_URL=http://localhost:3555
      - NEXTAUTH_SECRET=WkN/yuhOv6yENvPRXkca82HW3zETm4OCNNIdD9fsBx0=

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    ports:
      - "8000:8000"

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: my_mysql
    ports:
      - "5634:5634"
    environment:
      MYSQL_ROOT_PASSWORD: ano_sono2
      MYSQL_DATABASE: ano_sono2
      MYSQL_USER: ano_sono2
      MYSQL_PASSWORD: ano_sono2
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: