version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    ports:
      - "3555:3555"
    environment:
      - NEXTAUTH_URL=http://localhost:3555
      - NEXTAUTH_SECRET=msjAoFmPoPVor6+PoamBb4PwAauB1U4IpbkRtiPBYek=
      - FRONTEND_URL=http://localhost:3555
      - BACKEND_URL=http://localhost:8000
      - PORT=3555

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/logs

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: my_mysql
    ports:
      - "5634:5634"
    environment:
      MYSQL_ROOT_PASSWORD: ano_sono2
      MYSQL_DATABASE: ano_sono2
      MYSQL_USER: ano_sono2
      MYSQL_PASSWORD: ano_sono2
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  mysql_data:
