CREATE TABLE URL_STORAGE (
    ID INT AUTO_INCREMENT,
    TITLE VARCHAR(100) NOT NULL,
    URL VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(200),
    INSERT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID, URL)
);

CREATE TABLE USER_MASTER (
    ID INT AUTO_INCREMENT,
    USER_NAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    SALT VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE,
    INSERT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID, USER_NAME, EMAIL)
);




