CREATE TABLE URL_STORAGE (
    ID INT AUTO_INCREMENT,
    TITLE VARCHAR(100) NOT NULL,
    URL VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(200),
    INSERT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID, URL)
);