spring:
  datasource:
    url: jdbc:oracle:thin:@DESKTOP-MMJJAVE:1521/XEPDB1
    username: SpringProject
    password: H19890123h
    driver-class-name: oracle.jdbc.OracleDriver
  mvc:
    static-path-pattern: /static/**
  application:
    name: ano_sono
server:
  port : 8000
mybatis:
  mapper-locations: classpath*:com/project/mapper/*.xml
